# Generated by Django 4.2.1 on 2023-10-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TDEV", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="utilisateur",
            options={},
        ),
        migrations.AlterModelTable(
            name="utilisateur",
            table="Utilisateur",
        ),
    ]
